version: '3'
services:

  hc-di-admin-yarp:
    image: "biztalkless.azurecr.io/hc-di-yarp-basic:v1-win-nano-1809"
    pull_policy: always
    deploy:
      replicas: 1
    ports:
      - "44390:443"
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=44390
      - ASPNETCORE_Kestrel__Certificates__Default__Password=aa1234BB
      - ASPNETCORE_Kestrel__Certificates__Default__Path=c:\https\cert-localhost.pfx
      - Yarp__UrlProxyTo=http://hc-di-admin
    volumes:
       - C:\DockerVolumes\https:c:\https:rw
    restart: always

  hc-di-admin:
    image: "biztalkless.azurecr.io/hc-di-admin:v1-win-ltsc2019"
    pull_policy: always
    deploy:
      replicas: 1
    ports:
      - "8090:80"
    environment:
      - ExtraSql=di-sql-1.progel.org\hconnect,1437
    restart: always

  hc-di-user-yarp:
    image: "biztalkless.azurecr.io/hc-di-yarp-b2c:v1-win-nano-1809"
    pull_policy: always
    deploy:
      replicas: 1
    ports:
      - "44380:443"
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=44380
      - ASPNETCORE_Kestrel__Certificates__Default__Password=aa1234BB
      - ASPNETCORE_Kestrel__Certificates__Default__Path=c:\https\cert-localhost.pfx
      - Yarp__UrlProxyTo=http://hc-di-user
    volumes:
       - C:\DockerVolumes\https:c:\https:rw
    restart: always

  hc-di-user:
    image: "biztalkless.azurecr.io/hc-di-user:v1-win-ltsc2019"
    pull_policy: always
    deploy:
      replicas: 1
    ports:
      - "8080:80"
    environment:
      - ExtraSql=di-sql-1.progel.org\hconnect,1437
    restart: always

  hc-di-ws-dwh:
    image: "biztalkless.azurecr.io/hc-di-ws-dwh:v1-win-ltsc2019"
    pull_policy: always
    deploy:
      replicas: 2
    environment:
      - ExtraSql=di-sql-1.progel.org\hconnect,1437
    restart: always

  hc-di-ws-oe:
    image: "biztalkless.azurecr.io/hc-di-ws-oe:v1-win-ltsc2019"
    pull_policy: always
    deploy:
      replicas: 2
    environment:
      - ExtraSql=di-sql-1.progel.org\hconnect,1437
    restart: always

  hc-di-ws-sac:
    image: "biztalkless.azurecr.io/hc-di-ws-sac:v1-win-ltsc2019"
    pull_policy: always
    deploy:
      replicas: 2
    environment:
      - ExtraSql=di-sql-1.progel.org\hconnect,1437
    restart: always
    
  hc-di-ws-s3:
    image: "biztalkless.azurecr.io/hc-di-ws-s3:v1-win-nano-1809"
    pull_policy: always
    deploy:
      replicas: 2
    environment:
      - ASPNETCORE_URLS=http://+
      - ApplicationInsights__InstrumentationKey=47f2a002-85e4-4b5b-af93-bb848e0c7a4a
      - Service__FileCacheExpiredMinute=15
      - Service__PathBase=WS-DI-S3
    restart: always

  hc-di-ws:
    image: "biztalkless.azurecr.io/di-ws-nginx:1.23.1-win-ltsc2019"
    pull_policy: always
    deploy:
      replicas: 1
    tty: true
    ports:
      - "8070:80"
    restart: always

networks:
  default:
    name: nat
    external: true
