version: '3'
services:

  host-send-referti:
    image: "biztalkless.azurecr.io/dwh-bus-host-send:v1-win-nano-1809"
    deploy:
      replicas: 1
    environment:
      - StartupLogger__LoggingUrl=http://di-bt-1.progel.org:5341
      - ApplicationInsights__InstrumentationKey=137d619d-c491-40b7-ad25-b33124a14470
      - BusConfig__HostName=di-mq-1.progel.org
      - BusConfig__UserName=configClient
      - BusConfig__Password=aa1234BB
      - Settings__PublishReferti=true
      - Settings__PublishEventi=false
      - Settings__PublishNoteAnam=false
      - Settings__PublishPrescrizioni=false

  host-send-eventi:
    image: "biztalkless.azurecr.io/dwh-bus-host-send:v1-win-nano-1809"
    deploy:
      replicas: 1
    environment:
      - StartupLogger__LoggingUrl=http://di-bt-1.progel.org:5341
      - StartupLogger__LoggingApiKey=a6XHd6DCjKSe7rHB2L4X
      - ApplicationInsights__InstrumentationKey=137d619d-c491-40b7-ad25-b33124a14470
      - BusConfig__HostName=di-mq-1.progel.org
      - BusConfig__UserName=configClient
      - BusConfig__Password=aa1234BB
      - Settings__PublishReferti=false
      - Settings__PublishEventi=true
      - Settings__PublishNoteAnam=false
      - Settings__PublishPrescrizioni=false

  host-send-noteanam:
    image: "biztalkless.azurecr.io/dwh-bus-host-send:v1-win-nano-1809"
    deploy:
      replicas: 1
    environment:
      - StartupLogger__LoggingUrl=http://di-bt-1.progel.org:5341
      - StartupLogger__LoggingApiKey=a6XHd6DCjKSe7rHB2L4X
      - ApplicationInsights__InstrumentationKey=137d619d-c491-40b7-ad25-b33124a14470
      - BusConfig__HostName=di-mq-1.progel.org
      - BusConfig__UserName=configClient
      - BusConfig__Password=aa1234BB
      - Settings__PublishReferti=false
      - Settings__PublishEventi=false
      - Settings__PublishNoteAnam=true
      - Settings__PublishPrescrizioni=false

  host-send-prescrizioni:
    image: "biztalkless.azurecr.io/dwh-bus-host-send:v1-win-nano-1809"
    deploy:
      replicas: 1
    environment:
      - StartupLogger__LoggingUrl=http://di-bt-1.progel.org:5341
      - StartupLogger__LoggingApiKey=a6XHd6DCjKSe7rHB2L4X
      - ApplicationInsights__InstrumentationKey=137d619d-c491-40b7-ad25-b33124a14470
      - BusConfig__HostName=di-mq-1.progel.org
      - BusConfig__UserName=configClient
      - BusConfig__Password=aa1234BB
      - Settings__PublishReferti=false
      - Settings__PublishEventi=false
      - Settings__PublishNoteAnam=false
      - Settings__PublishPrescrizioni=true

networks:
  default:
    name: nat
    external: true
