version: '3'
services:
  rabbitmq:
    image: "alessandronostini/deploy:rabbitmq-3-win-ltsc2019"
    hostname: "rabbitmq"
    ports:
      - "15672:15672"
    restart: always

  consumer:
    image: "alessandronostini/deploy:masstransit-consumer-nanoserver-1809"
    deploy:
      replicas: 1
    environment:
      - Bus__HostName=rabbitmq
      - Bus__UserName=guest
      - Bus__Password=guest
    restart: always

  producer:
    image: "alessandronostini/deploy:masstransit-producer-nanoserver-1809"
    deploy:
      replicas: 1
    environment:
      - Bus__HostName=rabbitmq
      - Bus__UserName=guest
      - Bus__Password=guest
    restart: always

networks:
  default:
    name: nat
    external: true
